# Generated by Django 4.1 on 2022-08-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="タイトル")),
                ("content", models.TextField(verbose_name="本文")),
                (
                    "posted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="カテゴリ"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("science", "科学について"),
                            ("dailylife", "日常について"),
                            ("music", "音楽について"),
                        ],
                        max_length=50,
                        verbose_name="カテゴリ",
                    ),
                ),
            ],
        ),
    ]
